name: Resume Sync to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - "resume-sync/**"
  workflow_dispatch: # Allow manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  sync-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::931633655568:role/GitHubPortfolioDeploy
          aws-region: us-east-1
          role-session-name: ResumeSync

      - name: Clear S3 bucket contents
        run: |
          echo "🧹 Clearing existing files from resume-umarzaman-ca bucket..."
          aws s3 rm s3://resume-umarzaman-ca/ --recursive || echo "⚠️  Bucket was already empty or doesn't exist"

      - name: Sync resume to S3
        run: |
          # Check if resume file exists
          if [ -f "resume-sync/Umar_Zaman_Cloud_Engineer.pdf" ]; then
            echo "📄 Found resume file, syncing to S3..."
            aws s3 cp resume-sync/Umar_Zaman_Cloud_Engineer.pdf s3://resume-umarzaman-ca/ --cache-control max-age=31536000,public
            echo "✅ Resume synced successfully to resume-umarzaman-ca bucket"
          else
            echo "❌ No resume file found in resume-sync/ directory"
            exit 1
          fi

      - name: List S3 bucket contents
        run: |
          echo "📋 Current contents of resume-umarzaman-ca bucket:"
          aws s3 ls s3://resume-umarzaman-ca/ --recursive

      - name: Get resume URL
        run: |
          echo "🔗 Resume URL: https://resume-umarzaman-ca.s3.amazonaws.com/Umar_Zaman_Cloud_Engineer.pdf"
